### PR TITLE
update 

### PR DESCRIPTION
**Pull request by TomTravis**
add packages
-----------------------------------------------------------------------
GMAT uses:
- wxWidgets 3.0.4 (http://www.wxwidgets.org/)
- TSPlot (http://sourceforge.net/projects/tsplot/)
- SPICE (http://naif.jpl.nasa.gov/naif/toolkit.html)
- SOFA (http://www.iausofa.org/)
- Apache Xerces (http://xerces.apache.org/)
- JPL SPICE (https://naif.jpl.nasa.gov/naif/)  should his be here twice??
- OpenFramesInterface (https://gitlab.com/EmergentSpaceTechnologies/OpenFramesInterface)
- Boost (http://www.boost.org/)
- f2c (http://www.netlib.org/f2c)
- MSISE 1990 Density Model (https://ccmc.gsfc.nasa.gov/modelweb/atmos/msis.html)
- IRI 2007 Ionosphere Model (https://ccmc.gsfc.nasa.gov/modelweb/ionos/iri.html)

Planetary images are courtesy of: 
- JPL/Caltech/USGS (http://maps.jpl.nasa.gov/)
- Celestia Motherlode (http://www.celestiamotherlode.net/)
- Bjorn Jonsson (http://www.mmedia.is/~bjj/)
- NASA World Wind (http://worldwind.arc.nasa.gov/)

Some icons are courtesy of Mark James ( http://www.famfamfam.com/ )

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
Is this an update from the source forge repo?

**Comment by TomTravis** [comment]
Is what ?

No i did the effort to attempt to start compile the code on github as a
project, GMAT need lots of work
I hope the DOD STEM Program can take it over https://dodstem.us/
NSF has also been contacted
I finally have git working with local repo to update remote repo, this took
1 day of work
https://github.com/TomTravis/GMAT-1

The https://www.linuxlinks.com/orsa/ code is also not working, the install
is broken and the package needs to be updated.
GMAT needs a lot of work. The new how to compile is now updated\
The JPL code is also not compiled yet.

**Comment by TomTravis** [comment]
i hope you will join for ESA effort
https://github.com/users/TomTravis/projects/1/views/1

**Comment by ChristopherRabotin** [comment]
I'm afraid you're knocking on the wrong door. I'm only hosting the 2020a GMAT code without any changes, nor do I plan to add any, or push to this repo any changes made by others that aren't in the official release of GMAT. I use the GMAT source code in some parts to write [Nyx](https://nyxspace.com/) which is a high fidelity astrodynamics tool, used on two lunar missions. I put it publicly here hoping some people might like the ability to search the source code since Sourceforge does not allow for that.

Hence, I think it's best for your custom changes to exist on your repo but not on this one. I hope you understand.

**Comment by TomTravis** [comment]
yes i trying the 5 /2022 compile instructions  for gmat

i have no look at Nyx yet i will take a look

thank you

**Comment by TomTravis** [comment]
Hello chris I  have not idea to make changes on your repo code
configuration control does this

I will download nyx from Git lab today. I do not have an account yet.
I have been using a computer for a long time now. THe DOD stem Program got
back to me. It is a university of California activity, Los Angeles.

It appears you like rust. Some of my friends use this all the time. i'm
still cli for the most part, the GUI is too slow.
NASA Is NASA they are not very good at code management, never have been.

**Pull request closed without merging**
